import { chromium } from 'playwright';
const base=process.env.SITE_URL||'https://ielts-kenyacenter.or.ke'; const supabaseUrl=process.env.SUPABASE_URL; const adminKey=process.env.SUPABASE_SECRET_KEY; const failures=[]; const checks=[];
const ok=(name,detail='')=>checks.push({name,detail}); const fail=(name,detail)=>{failures.push({name,detail});console.error(`FAIL: ${name}: ${detail}`)};
const adminHeaders=()=>({apikey:adminKey,Authorization:`Bearer ${adminKey}`,'Content-Type':'application/json'});
async function adminDeleteUser(id){if(!id||!supabaseUrl||!adminKey)return false;return (await fetch(`${supabaseUrl}/auth/v1/admin/users/${id}`,{method:'DELETE',headers:adminHeaders()})).ok}
async function adminCreateConfirmedUser(email,password){if(!supabaseUrl||!adminKey)return null;const r=await fetch(`${supabaseUrl}/auth/v1/admin/users`,{method:'POST',headers:adminHeaders(),body:JSON.stringify({email,password,email_confirm:true,user_metadata:{full_name:'Production QA Student'}})});const b=await r.json().catch(()=>({}));return r.ok?b:null}
async function main(){
 const browser=await chromium.launch({headless:true}); const context=await browser.newContext({viewport:{width:1440,height:900}}); const desktop=await context.newPage(); const consoleErrors=[]; const pageErrors=[];
 desktop.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())}); desktop.on('pageerror',e=>pageErrors.push(String(e)));
 const home=await desktop.goto(base+'/',{waitUntil:'networkidle'}); if(home?.ok())ok('Desktop homepage loads',`${home.status()}`);else fail('Desktop homepage loads',`HTTP ${home?.status()}`); if((await desktop.locator('body').innerText()).includes('IELTS Kenya Center'))ok('Homepage branding');else fail('Homepage branding','text missing');
 const mobile=await context.newPage({viewport:{width:390,height:844}}); const mobileErrors=[];mobile.on('console',m=>{if(m.type()==='error')mobileErrors.push(m.text())});mobile.on('pageerror',e=>mobileErrors.push(String(e)));const mh=await mobile.goto(base+'/',{waitUntil:'networkidle'});if(mh?.ok())ok('Mobile homepage loads',`${mh.status()}`);else fail('Mobile homepage loads',`HTTP ${mh?.status()}`);if(mobileErrors.length)fail('Mobile console',mobileErrors.slice(0,5).join(' | '));else ok('Mobile console','none');
 for(const path of ['/courses','/dashboard','/practice','/resources','/forgot-password','/reset-password']){const r=await desktop.goto(base+path,{waitUntil:'domcontentloaded'});if(r?.ok())ok(`Direct route refresh ${path}`,`${r.status()}`);else fail(`Direct route refresh ${path}`,`HTTP ${r?.status()}`)}
 await desktop.goto(base+'/forgot-password',{waitUntil:'networkidle'}); if((await desktop.locator('body').innerText()).includes('Forgot your password?'))ok('Forgot Password page');else fail('Forgot Password page','content missing');
 const health=await desktop.request.get(base+'/api/_healthcheck');if(health.ok()&&(await health.json()).ok===true)ok('Worker healthcheck');else fail('Worker healthcheck',`HTTP ${health.status()}`);
 const cfg=await desktop.request.get(base+'/api/config-status');if(cfg.ok()&&(await cfg.json()).supabaseConfigured===true)ok('Supabase runtime configuration');else fail('Supabase runtime configuration',`HTTP ${cfg.status()}`);
 const es=await desktop.request.post(base+'/api/email/status');if(es.ok()&&(await es.json()).configured===true)ok('Resend runtime configuration');else fail('Resend runtime configuration',`HTTP ${es.status()}`);
 const email=`qa-${Date.now()}-${Math.random().toString(36).slice(2,7)}@example.com`; const password='QaSmoke!'+Math.random().toString(36).slice(2,10)+'9';
 const signup=await desktop.request.post(base+'/api/auth/signup',{data:{fullName:'Production QA Student',email,password}});const sb=await signup.json().catch(()=>({}));if(signup.ok()&&sb.ok)ok('Student registration',sb.message);else fail('Student registration',`HTTP ${signup.status()} ${JSON.stringify(sb)}`);
 let userId=sb?.user?.id; if(!userId&&supabaseUrl&&adminKey){const list=await fetch(`${supabaseUrl}/auth/v1/admin/users?page=1&per_page=100`,{headers:adminHeaders()});if(list.ok){const b=await list.json();userId=b.users?.find(u=>u.email===email)?.id}}
 if(userId)ok('Supabase Auth user created');else fail('Supabase Auth user created','not found');
 if(userId&&supabaseUrl&&adminKey){const p=await fetch(`${supabaseUrl}/rest/v1/profiles?id=eq.${encodeURIComponent(userId)}&select=id,full_name`,{headers:adminHeaders()});const rows=p.ok?await p.json():[];if(rows.length===1)ok('Student profile created');else fail('Student profile created',`HTTP ${p.status} rows=${rows.length}`)}
 if(sb?.needsEmailVerification)ok('Email verification required state','No email-verification pass was faked; signup returned verification-required.');
 let sign=await desktop.request.post(base+'/api/auth/signin',{data:{email,password}}); let authenticated=sign.ok(); if(authenticated)ok('Sign in'); else if(userId&&supabaseUrl&&adminKey){const c=await fetch(`${supabaseUrl}/auth/v1/admin/users/${userId}`,{method:'PUT',headers:adminHeaders(),body:JSON.stringify({email_confirm:true})});if(c.ok){ok('QA verification bypass for downstream tests','admin-confirmed QA account only');sign=await desktop.request.post(base+'/api/auth/signin',{data:{email,password}});authenticated=sign.ok();if(authenticated)ok('Sign in after QA confirmation');}else fail('QA verification bypass for downstream tests',`HTTP ${c.status}`)}
 let courseId=''; let lessonId='';
 if(authenticated){const me=await desktop.request.get(base+'/api/auth/me');if(me.ok()&&(await me.json()).user?.id===userId)ok('Session identity');else fail('Session identity',`HTTP ${me.status()}`);await desktop.goto(base+'/dashboard',{waitUntil:'networkidle'});if((await desktop.locator('body').innerText()).includes('Student Dashboard'))ok('Dashboard UI');else fail('Dashboard UI','missing');const d=await desktop.request.get(base+'/api/learning/dashboard');const db=await d.json().catch(()=>({}));if(d.ok()&&db.courses?.length===4)ok('Course loading','4 published courses');else fail('Course loading',`HTTP ${d.status()} ${JSON.stringify(db)}`);courseId=db.courses?.[0]?.id||'';if(courseId){const en=await desktop.request.post(base+'/api/learning/enroll',{data:{courseId}});if(en.ok())ok('Enrollment');else fail('Enrollment',`HTTP ${en.status()}`)}
  if(courseId){const cr=await desktop.request.get(base+`/api/learning/courses/${courseId}`);const cb=await cr.json().catch(()=>({}));if(cr.ok()&&cb.modules?.length&&cb.lessons?.length){ok('Module loading',`modules=${cb.modules.length}`);ok('Lesson loading',`lessons=${cb.lessons.length}`);lessonId=cb.lessons[0].id}else fail('Module/lesson loading',`HTTP ${cr.status()} ${JSON.stringify(cb)}`)}
  if(lessonId){await desktop.goto(base+`/lesson/${lessonId}`,{waitUntil:'networkidle'});if((await desktop.locator('body').innerText()).length>50)ok('Lesson UI and direct refresh');else fail('Lesson UI and direct refresh','empty');const lr=await desktop.request.get(base+`/api/learning/lessons/${lessonId}`);if(lr.ok()&&(await lr.json()).lesson?.id===lessonId)ok('Lesson content loading');else fail('Lesson content loading',`HTTP ${lr.status()}`);const pr=await desktop.request.put(base+'/api/learning/progress',{data:{lessonId,percent:100,status:'completed'}});const pb=await pr.json().catch(()=>({}));if(pr.ok()&&pb.progress?.status==='completed')ok('Lesson progress save');else fail('Lesson progress save',`HTTP ${pr.status()} ${JSON.stringify(pb)}`);const pr2=await desktop.request.get(base+`/api/learning/lessons/${lessonId}`);if(pr2.ok()&&(await pr2.json()).progress?.status==='completed')ok('Lesson progress persistence');else fail('Lesson progress persistence',`HTTP ${pr2.status()}`);const rr=await desktop.goto(base+`/courses/${courseId}`,{waitUntil:'networkidle'});if(rr?.ok())ok('Course direct refresh');else fail('Course direct refresh',`HTTP ${rr?.status()}`)}
  await desktop.request.post(base+'/api/auth/signout');const mo=await desktop.request.get(base+'/api/auth/me');if(mo.ok()&&!(await mo.json()).user)ok('Logout');else fail('Logout',`HTTP ${mo.status()}`);const si=await desktop.request.post(base+'/api/auth/signin',{data:{email,password}});if(si.ok())ok('Sign back in');else fail('Sign back in',`HTTP ${si.status()}`);const rf=await desktop.reload({waitUntil:'networkidle'});if(rf?.ok())ok('Session persistence after refresh');else fail('Session persistence after refresh',`HTTP ${rf?.status()}`);
 }
 const unauth=await desktop.request.post(base+'/api/auth/signout');const pd=await desktop.request.get(base+'/api/learning/dashboard');if(pd.status()===401)ok('Unauthenticated dashboard protection');else fail('Unauthenticated dashboard protection',`HTTP ${pd.status()}`);
 if(userId&&courseId){const e2=`qa-isolation-${Date.now()}@example.com`;const p2='QaIso!'+Math.random().toString(36).slice(2,10)+'9';const u2=await adminCreateConfirmedUser(e2,p2);const id2=u2?.user?.id;if(id2){const s2=await desktop.request.post(base+'/api/auth/signin',{data:{email:e2,password:p2}});if(s2.ok()){const denied=await desktop.request.get(base+`/api/learning/courses/${courseId}`);if(denied.status()===403)ok('RLS/student isolation');else fail('RLS/student isolation',`HTTP ${denied.status()}`)}else fail('RLS/student isolation','second sign-in failed');await adminDeleteUser(id2)}else fail('RLS/student isolation','second QA user not created')}
 const secretNames=['SUPABASE_SECRET_KEY','RESEND_API_KEY','CLOUDFLARE_API_TOKEN'];const scripts=await desktop.evaluate(()=>Array.from(document.scripts).map(s=>s.src).filter(Boolean));for(const u of scripts){const r=await desktop.request.get(u);const t=await r.text();for(const n of secretNames)if(t.includes(n))fail('Browser secret exposure',`${n} found in ${u}`)}ok('Browser bundle secret scan','no server secret names');
 const expected401=consoleErrors.filter(e=>!e.includes('401'));if(expected401.length)fail('Desktop console',expected401.slice(0,5).join(' | '));else ok('Desktop console','no unexpected console errors');if(pageErrors.length)fail('Browser page errors',pageErrors.slice(0,5).join(' | '));else ok('Browser page errors','none');
 if(userId&&await adminDeleteUser(userId))ok('QA account cleanup'); await browser.close();console.log(JSON.stringify({checks,failures},null,2));if(failures.length)process.exit(1);
}
main().catch(e=>{console.error(e);process.exit(1)});
