import baseWorker from './index';
interface Env { ASSETS: { fetch: (request: Request) => Promise<Response> }; SUPABASE_URL: string; SUPABASE_PUBLISHABLE_KEY: string; SUPABASE_SECRET_KEY: string; RESEND_API_KEY: string; CLOUDFLARE_API_TOKEN?: string; OPS_SETUP_KEY?: string; }
const origin='https://ielts-kenyacenter.or.ke'; const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8'}}); const safe=(v:string)=>v.replace(/[<>&\"']/g,'');
async function adminGenerateLink(env:Env,payload:Record<string,unknown>){const response=await fetch(`${env.SUPABASE_URL}/auth/v1/admin/generate_link`,{method:'POST',headers:{apikey:env.SUPABASE_SECRET_KEY,'Content-Type':'application/json'},body:JSON.stringify(payload)});const text=await response.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{}return{response,data}}
function actionLink(env:Env,data:any){return data?.action_link|| (data?.hashed_token&&data?.verification_type?`${env.SUPABASE_URL}/auth/v1/verify?token=${encodeURIComponent(data.hashed_token)}&type=${encodeURIComponent(data.verification_type)}&redirect_to=${encodeURIComponent(data.redirect_to||origin)}`:'')}
async function sendAuthEmail(env:Env,to:string,subject:string,title:string,intro:string,link:string,text:string){const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:'IELTS Kenya Center <admin@ielts-kenyacenter.or.ke>',to:[to],subject,html:`<div style="font-family:Arial,sans-serif;line-height:1.6;max-width:620px;margin:auto;color:#18221f"><h2>${title}</h2><p>${intro}</p><p><a href="${link}" style="display:inline-block;background:#1e6b55;color:#fff;text-decoration:none;padding:12px 18px;border-radius:8px;font-weight:700">${text}</a></p><p style="font-size:13px;color:#666">This secure link is single-use and expires according to your Supabase Auth settings.</p><p style="font-size:13px;color:#666">IELTS Kenya Center • Prepare • Practice • Achieve</p></div>`})});return response.ok}
export default{async fetch(request:Request,env:Env,ctx:ExecutionContext){const url=new URL(request.url);
if(request.method==='POST'&&url.pathname==='/api/auth/signup'){let body:any={};try{body=await request.json()}catch{return json({message:'Invalid request body.'},400)}if(!body.email||!body.password||!body.fullName)return json({message:'Full name, email and password are required.'},400);if(String(body.password).length<8)return json({message:'Password must be at least 8 characters.'},400);const email=String(body.email).trim(),fullName=String(body.fullName).trim();const generated=await adminGenerateLink(env,{type:'signup',email,password:String(body.password),data:{full_name:fullName},redirect_to:origin});if(!generated.response.ok)return json({message:generated.data?.msg||generated.data?.message||`Supabase Auth link generation failed (HTTP ${generated.response.status}).`},generated.response.status);const link=actionLink(env,generated.data),user=generated.data?.id?generated.data:null;if(!link||!user)return json({message:'Supabase Auth did not return a usable verification link.'},502);const sent=await sendAuthEmail(env,email,'Verify your IELTS Kenya Center account',`Welcome to IELTS Kenya Center, ${safe(fullName)}`,'Your learner account is ready. Please verify your email address to activate sign-in and access your learning dashboard.',link,'Verify email address');if(!sent)return json({message:'Your account was created, but we could not deliver the verification email.'},502);return json({ok:true,user,needsEmailVerification:true,welcomeEmailAccepted:true,message:'Account created. Check your email to verify your account before signing in.'})}
if(request.method==='POST'&&url.pathname==='/api/auth/recover'){let body:any={};try{body=await request.json()}catch{return json({message:'Invalid request body.'},400)}if(!body.email)return json({message:'Email address is required.'},400);const email=String(body.email).trim();const generated=await adminGenerateLink(env,{type:'recovery',email,redirect_to:origin});if(generated.response.ok){const link=actionLink(env,generated.data);if(link)ctx.waitUntil(sendAuthEmail(env,email,'Reset your IELTS Kenya Center password','Reset your IELTS Kenya Center password','We received a request to change the password for your learner account. Use the secure link below to choose a new password.',link,'Choose a new password'))}return json({ok:true,message:'If an account exists for that email, a password recovery link has been sent.'})}
return baseWorker.fetch(request,env)}};
