import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Headphones, BookOpen, Mic2, PenLine, ShieldCheck } from 'lucide-react';
import { isListeningAnswerCorrect, listeningPartOne } from './listeningPractice';
const green='#176b4f', red='#d10b16', ink='#171b1a', paper='#f7f5ef', line='#e5e1d7';
type Skill='listening'|'reading'|'writing'|'speaking';
const skills=[['listening','Listening',Headphones,'10-question original practice'],['reading','Reading',BookOpen,'Timed passage — next phase'],['writing','Writing',PenLine,'Task 1 & Task 2 — next phase'],['speaking','Speaking',Mic2,'Speaking workspace — next phase']] as const;
const box={background:'#fff',border:`1px solid ${line}`,borderRadius:20,padding:24,boxShadow:'0 12px 35px rgba(24,34,31,.05)'} as const;
const primary={display:'inline-flex',alignItems:'center',justifyContent:'center',gap:8,border:0,borderRadius:10,padding:'12px 17px',background:red,color:'#fff',fontWeight:900,cursor:'pointer'} as const;
export function MockTestsPage(){
 const [skill,setSkill]=useState<Skill>('listening'),[started,setStarted]=useState(false),[answers,setAnswers]=useState<Record<number,string>>({}),[seconds,setSeconds]=useState(720),[submitted,setSubmitted]=useState(false);
 useEffect(()=>{if(!started||submitted||skill!=='listening')return;const t=setInterval(()=>setSeconds(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[started,submitted,skill]);
 const score=useMemo(()=>listeningPartOne.questions.reduce((n,q)=>n+(isListeningAnswerCorrect(answers[q.id]||'',q.answer)?1:0),0),[answers]);
 const answered=Object.values(answers).filter(Boolean).length,time=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
 const reset=()=>{setStarted(false);setSubmitted(false);setAnswers({});setSeconds(720)};
 if(started)return <main style={{minHeight:'100vh',background:paper,color:ink}}><div style={{maxWidth:1100,margin:'auto',padding:'22px 18px'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:12,borderBottom:`1px solid ${line}`,paddingBottom:18}}><button onClick={reset} style={{...primary,background:'#fff',color:ink,border:`1px solid ${line}`}}><ArrowLeft size={17}/> Exit</button><strong>IELTS KENYA CENTER<br/><small style={{color:green}}>LISTENING PRACTICE</small></strong><strong><Clock3 size={17}/> {time}</strong></header><section style={{...box,marginTop:20}}><span style={{color:green,fontWeight:900,fontSize:12,letterSpacing:1.5}}>ORIGINAL IELTS-STYLE PRACTICE</span><h1>{listeningPartOne.title}</h1><p>{listeningPartOne.context}</p><div style={{background:'#eef5f1',padding:16,borderRadius:14}}><strong>Instructions</strong><p>Use the original transcript and complete each answer. This is preparation content, not an official IELTS test.</p><details><summary>Open transcript</summary><pre style={{whiteSpace:'pre-wrap'}}>{listeningPartOne.script}</pre></details></div><div style={{display:'grid',gap:12,marginTop:20}}>{listeningPartOne.questions.map(q=><label key={q.id} style={{padding:14,border:`1px solid ${line}`,borderRadius:12}}><strong>{q.id}. {q.prompt}</strong><input value={answers[q.id]||''} onChange={e=>setAnswers(v=>({...v,[q.id]:e.target.value}))} placeholder={q.placeholder||'Your answer'} style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:8,padding:11,border:`1px solid ${line}`,borderRadius:9,fontSize:16}}/></label>)}</div>{submitted?<div style={{marginTop:20,padding:20,borderRadius:14,background:'#edf8f2'}}><CheckCircle2 color={green}/><h2>Practice complete</h2><p>Score: <strong>{score}/{listeningPartOne.questions.length}</strong></p><p>This is a practice indicator only, not an official IELTS band score.</p><button onClick={reset} style={primary}>Try again</button></div>:<button disabled={!answered} onClick={()=>setSubmitted(true)} style={{...primary,marginTop:20,opacity:answered?1:.5}}>Submit practice <ArrowRight size={17}/></button>}</section></div></main>;
 return <main style={{minHeight:'100vh',background:paper,color:ink}}><header style={{background:'#fff',borderBottom:`1px solid ${line}`}}><div style={{maxWidth:1180,margin:'auto',padding:16,display:'flex',justifyContent:'space-between',alignItems:'center'}}><a href="/"><img src="/logo.svg" alt="IELTS Kenya Center" style={{width:180}}/></a><a href="/dashboard" style={{fontWeight:800,color:ink}}>Candidate dashboard</a></div></header><div style={{maxWidth:1180,margin:'auto',padding:'48px 18px'}}><section style={{display:'grid',gridTemplateColumns:'1.4fr .6fr',gap:28}}><div style={{...box,padding:34}}><span style={{color:green,fontWeight:900,fontSize:12,letterSpacing:1.8}}>MOCK TEST CENTER</span><h1 style={{fontSize:'clamp(36px,6vw,58px)',lineHeight:1.02}}>Practise with purpose.</h1><p style={{fontSize:18,lineHeight:1.6}}>Structured IELTS-style practice for learners. Start with Listening today and expand the four-skill experience in phases.</p><span style={{display:'inline-flex',gap:7,padding:8,borderRadius:999,background:'#eef5f1',color:green,fontWeight:800}}><ShieldCheck size={15}/> Learner preparation</span></div><div style={{...box,background:ink,color:'#fff',borderColor:ink}}><span style={{color:'#8ed1b5',fontWeight:900,fontSize:12}}>YOUR PRACTICE HUB</span><h2>Four skills. One pathway.</h2>{skills.map(([id,label,Icon,detail])=><button key={id} onClick={()=>setSkill(id)} style={{display:'block',width:'100%',textAlign:'left',padding:12,marginTop:8,borderRadius:11,border:skill===id?'1px solid #8ed1b5':'1px solid #3b4541',background:skill===id?'#234f40':'transparent',color:'#fff'}}><Icon size={17}/> <strong>{label}</strong><small style={{display:'block',color:'#b6c1bc',marginTop:3}}>{detail}</small></button>)}</div></section><section style={{...box,marginTop:28}}><span style={{color:green,fontWeight:900,fontSize:12}}>SELECTED SKILL</span><h2>{skills.find(s=>s[0]===skill)?.[1]} practice</h2><p>{skills.find(s=>s[0]===skill)?.[3]}</p>{skill==='listening'?<button onClick={()=>setStarted(true)} style={primary}>Start Listening practice <ArrowRight size={17}/></button>:<div style={{padding:16,borderRadius:12,background:paper}}><strong>This skill is coming next.</strong><p>The Mock Test Center is being expanded in phases with dedicated questions, timing, answer handling and result tracking.</p></div>}</section></div></main>;
}
